nome=str(input('Digite seu nome Completo ?')).strip()
print('Estamos Analisando...')
print('Seu nome em Maiuscúlas é {} :'.format(nome.upper()))
print('Seu nome em Minuscúlas é {} :'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
